# Generated by Django 3.1.4 on 2020-12-19 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام سینما')),
                ('capacity', models.IntegerField(verbose_name='ظرفیت سینما')),
                ('city', models.CharField(default='تهران', max_length=50, verbose_name='شهر')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='شماره تماس')),
                ('image', models.ImageField(upload_to='files/Cinema_Images', verbose_name='عکس')),
                ('address', models.TextField(verbose_name='آدرس')),
            ],
            options={
                'verbose_name': 'سینما',
                'verbose_name_plural': 'سینما',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام فیلم')),
                ('director', models.CharField(max_length=50, verbose_name='کارگردان')),
                ('cover', models.ImageField(upload_to='files/Movie_Covers', verbose_name='عکس')),
                ('length', models.IntegerField(verbose_name='مدت فیلم')),
                ('year', models.IntegerField(verbose_name='سال ساخت')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'فیلم',
                'verbose_name_plural': 'فیلم',
            },
        ),
        migrations.CreateModel(
            name='ShowTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='زمان شروع سانس')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('salable_seats', models.IntegerField(verbose_name='تعداد صندلی های قابل فروش')),
                ('free_seats', models.IntegerField(verbose_name='تعداد صندلی های خالی')),
                ('status', models.IntegerField(choices=[(1, 'فروش بلیت شروع شد'), (2, 'فروش بلیت آغاز نشده'), (3, 'بلیت ها تمام شدند'), (4, 'سانس لغو شد'), (5, 'فیلم تمام شد'), (6, 'فروش بلیت بسته شد')], default=2, verbose_name='وضعیت')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.cinema', verbose_name='سینما')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.movie', verbose_name='فیلم')),
            ],
            options={
                'verbose_name': 'سانس',
                'verbose_name_plural': 'سانس',
            },
        ),
    ]
