# Generated by Django 3.1.4 on 2021-01-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='image',
            field=models.ImageField(upload_to='Cinema_Images/', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cover',
            field=models.ImageField(upload_to='Movie_Covers/', verbose_name='عکس'),
        ),
    ]
