# Generated by Django 3.1.4 on 2021-03-30 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0004_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showtime',
            name='salable_seats',
        ),
    ]
