# Generated by Django 3.1.4 on 2021-04-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0005_remove_showtime_salable_seats'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False, verbose_name='کد خبر')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان خبر')),
                ('subject', models.CharField(max_length=50, verbose_name='موضوع خبر')),
                ('image', models.ImageField(upload_to='Movie_Covers/', verbose_name='عکس')),
                ('time', models.DateTimeField(verbose_name='زمان خبر')),
                ('text', models.TextField(verbose_name='متن خبر')),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'خبر',
            },
        ),
        migrations.AlterField(
            model_name='showtime',
            name='status',
            field=models.IntegerField(choices=[(1, 'فروش بلیت شروع شد'), (2, 'فروش بلیت آغاز نشده'), (3, 'بلیت ها تمام شدند'), (4, 'سانس لغو شد'), (5, 'فیلم تمام شد'), (6, 'فروش بلیت بسته شد')], default=((1, 'فروش بلیت شروع شد'), (2, 'فروش بلیت آغاز نشده'), (3, 'بلیت ها تمام شدند'), (4, 'سانس لغو شد'), (5, 'فیلم تمام شد'), (6, 'فروش بلیت بسته شد')), verbose_name='وضعیت'),
        ),
    ]
