# Generated by Django 3.1.4 on 2021-04-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0006_auto_20210405_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='News_Images/', verbose_name='عکس'),
        ),
    ]
