# Generated by Django 3.1.4 on 2021-03-25 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='accounts_avatar/', verbose_name='آواتار')),
                ('phone', models.IntegerField(max_length=20, verbose_name='تلفن همراه')),
                ('gender', models.IntegerField(blank=True, choices=[(1, 'زن'), (2, 'مرد')], null=True, verbose_name='جنسیت')),
                ('birthday', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('credit_money', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='اعتبار مالی')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('address', models.TextField(max_length=250, verbose_name='آدرس')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='حساب')),
            ],
        ),
    ]
