# Generated by Django 3.1.4 on 2021-03-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210325_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='Media/accounts_avatar/', verbose_name='آواتار'),
        ),
    ]
