# Generated by Django 3.1.4 on 2021-03-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210326_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='credit_money',
            field=models.IntegerField(default=0, verbose_name='اعتبار مالی'),
        ),
    ]
