# Generated by Django 3.1.4 on 2021-03-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210328_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(default='ایران', max_length=250, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(default='تبریز', max_length=100, verbose_name='شهر'),
        ),
    ]
