# Generated by Django 3.1.4 on 2021-03-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210329_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'مرد'), ('W', 'زن'), ('U', 'شخصی')], max_length=1, null=True, verbose_name='جنسیت'),
        ),
    ]
