# Generated by Django 3.1.4 on 2021-03-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210330_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'زن'), (2, 'مرد')], null=True, verbose_name='جنسیت'),
        ),
    ]
