# Generated by Django 3.1.4 on 2021-03-30 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'پروفایل کاربران', 'verbose_name_plural': 'پروفایل کاربران'},
        ),
    ]
